/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionairetudiant;

/**
 *
 * @author Elias
 */
public class AjouterModules extends javax.swing.JFrame {

    /**
     * Creates new form AjouterModules
     */
    public AjouterModules() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NomDeModul = new javax.swing.JTextField();
        Credit = new javax.swing.JTextField();
        Coeff = new javax.swing.JTextField();
        Abreviation = new javax.swing.JTextField();
        Unite = new javax.swing.JTextField();
        AddMod = new javax.swing.JButton();
        Retur = new javax.swing.JButton();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NomDeModul.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NomDeModul.setBorder(null);
        getContentPane().add(NomDeModul, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 124, 170, 30));

        Credit.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Credit.setAutoscrolls(false);
        Credit.setBorder(null);
        getContentPane().add(Credit, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 124, 70, 30));

        Coeff.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Coeff.setBorder(null);
        getContentPane().add(Coeff, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 124, 70, 30));

        Abreviation.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Abreviation.setBorder(null);
        getContentPane().add(Abreviation, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 201, 70, 30));

        Unite.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Unite.setBorder(null);
        getContentPane().add(Unite, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 201, 260, 30));

        AddMod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AjtModAddBn.png"))); // NOI18N
        getContentPane().add(AddMod, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 252, 180, 40));

        Retur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AjtModReturBn.png"))); // NOI18N
        Retur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturActionPerformed(evt);
            }
        });
        getContentPane().add(Retur, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 252, 180, 40));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AjouterModulBg.png"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturActionPerformed
        dispose();
        MainIntr main = new MainIntr();
        main.setVisible(true);
    }//GEN-LAST:event_ReturActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AjouterModules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AjouterModules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AjouterModules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AjouterModules.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AjouterModules().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Abreviation;
    private javax.swing.JButton AddMod;
    private javax.swing.JLabel Bg;
    private javax.swing.JTextField Coeff;
    private javax.swing.JTextField Credit;
    private javax.swing.JTextField NomDeModul;
    private javax.swing.JButton Retur;
    private javax.swing.JTextField Unite;
    // End of variables declaration//GEN-END:variables
}
