/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestionairetudiant;

/**
 *
 * @author Elias
 */
public class SaisirNote extends javax.swing.JFrame {

    /**
     * Creates new form SaisirNote
     */
    public SaisirNote() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReflachBn = new javax.swing.JButton();
        AddNotebn = new javax.swing.JButton();
        Retourbn = new javax.swing.JButton();
        NomEtud = new javax.swing.JTextField();
        NoteTD = new javax.swing.JTextField();
        NoteCor = new javax.swing.JTextField();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ReflachBn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ReflachBn.png"))); // NOI18N
        ReflachBn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ReflachBn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReflachBnActionPerformed(evt);
            }
        });
        getContentPane().add(ReflachBn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 500, 100, 50));

        AddNotebn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/AddnoteBn.png"))); // NOI18N
        AddNotebn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        AddNotebn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNotebnActionPerformed(evt);
            }
        });
        getContentPane().add(AddNotebn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1045, 443, 100, 50));

        Retourbn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/RetuaddnoteBn.png"))); // NOI18N
        Retourbn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(Retourbn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1175, 441, 100, 50));

        NomEtud.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NomEtud.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(NomEtud, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 128, 380, 40));

        NoteTD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NoteTD.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(NoteTD, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 235, 380, 40));
        NoteTD.getAccessibleContext().setAccessibleName("");

        NoteCor.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        NoteCor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(NoteCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 341, 380, 40));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/SisirnoteBg.png"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReflachBnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReflachBnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReflachBnActionPerformed

    private void AddNotebnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNotebnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddNotebnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaisirNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaisirNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaisirNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaisirNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaisirNote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNotebn;
    private javax.swing.JLabel Bg;
    private javax.swing.JTextField NomEtud;
    private javax.swing.JTextField NoteCor;
    private javax.swing.JTextField NoteTD;
    private javax.swing.JButton ReflachBn;
    private javax.swing.JButton Retourbn;
    // End of variables declaration//GEN-END:variables
}
